// Données du programme Muscu — portées depuis l'app native (SeedData.swift).
// PROGRAM_VERSION : bumper si on modifie le programme (déclenche une resynchro douce).
export const PROGRAM_VERSION = 1;

// Bibliothèque d'exercices (avec explications FR). Clé = id court.
export const EXERCISES = {
  presse: { name: "Presse à cuisses", group: "Jambes", equipment: "Machine",
    instructions: "Assis dans la presse, pieds à largeur de hanches au milieu du plateau. Descends en contrôlant jusqu'à ~90° aux genoux, puis pousse en gardant le bas du dos plaqué. Ne verrouille jamais les genoux en haut.",
    cues: ["Pieds à plat, pousse sur les talons", "Genoux dans l'axe des pieds", "Dos collé au dossier", "Ne bloque pas les genoux"],
    mistakes: ["Décoller les fesses en bas", "Amplitude trop courte", "Genoux qui rentrent"] },
  smithSquat: { name: "Squat à la Smith machine", group: "Jambes", equipment: "Smith",
    instructions: "Barre guidée sur le haut du dos, pieds légèrement devant la barre. Descends genoux+hanches jusqu'à la parallèle, remonte en poussant dans le sol.",
    cues: ["Pieds un peu en avant", "Descente contrôlée jusqu'à la parallèle", "Pousse sur tout le pied", "Gaine les abdos"],
    mistakes: ["Talons qui décollent", "Descente trop rapide", "Dos rond en bas"] },
  squat: { name: "Squat", group: "Jambes", equipment: "Barre",
    instructions: "Barre sur les trapèzes, pieds largeur d'épaules. Inspire, gaine, descends les hanches vers l'arrière jusqu'à la parallèle buste fier, remonte en poussant dans le sol.",
    cues: ["Gaine avant de descendre", "Genoux dans l'axe des pieds", "Poitrine haute", "Au moins à la parallèle"],
    mistakes: ["Dos qui s'arrondit", "Genoux qui rentrent", "Talons qui décollent"] },
  legExtension: { name: "Leg extension (quadriceps)", group: "Jambes", equipment: "Machine",
    instructions: "Assis, tends les jambes pour soulever le coussinet en contractant les quadriceps, pause en haut, redescends en contrôlant.",
    cues: ["Extension complète", "Pause en haut", "Retour lent"],
    mistakes: ["À-coups", "Charge trop lourde qui casse l'amplitude"] },
  legCurl: { name: "Leg curl (ischios)", group: "Jambes", equipment: "Machine",
    instructions: "Ramène le coussinet vers les fessiers en contractant les ischios, puis reviens lentement. Bassin stable.",
    cues: ["Mouvement contrôlé", "Contraction en flexion", "Bassin stable"],
    mistakes: ["Décoller le bassin", "À-coups"] },

  devCoucheHalteres: { name: "Développé couché haltères", group: "Pectoraux", equipment: "Haltères",
    instructions: "Allongé, haltères au-dessus de la poitrine. Descends les coudes à ~45° du buste jusqu'au niveau de la poitrine, pousse en rapprochant légèrement. Omoplates serrées, pieds au sol.",
    cues: ["Omoplates serrées et basses", "Coudes à 45°", "Amplitude complète", "Pieds ancrés"],
    mistakes: ["Coudes trop ouverts", "Cambrer excessivement", "Rebondir en bas"] },
  devCoucheBarre: { name: "Développé couché barre", group: "Pectoraux", equipment: "Barre",
    instructions: "Prise un peu plus large que les épaules. Descends vers le bas des pecs en contrôlant, frôle la poitrine, pousse jusqu'à l'extension.",
    cues: ["Trajectoire vers le bas des pecs", "Omoplates serrées", "Poignets au-dessus des coudes"],
    mistakes: ["Faire rebondir la barre", "Décoller les fesses", "Coudes trop ouverts"] },
  devInclineHalteres: { name: "Développé incliné haltères", group: "Pectoraux", equipment: "Haltères",
    instructions: "Banc incliné 30-45°. Descends jusqu'au niveau des clavicules puis pousse. Cible le haut des pectoraux.",
    cues: ["Inclinaison 30-45°", "Cible le haut des pecs", "Coudes à 45°"],
    mistakes: ["Banc trop incliné", "Amplitude écourtée"] },
  ecartePoulieBasse: { name: "Écarté poulie basse", group: "Pectoraux", equipment: "Poulie",
    instructions: "Poulies en bas, légèrement penché. Amène les mains vers le haut et le centre en contractant le haut des pectoraux, reviens lentement.",
    cues: ["Angle de coude fixe", "Rassemble vers le haut/centre", "Contracte en fin de mouvement"],
    mistakes: ["Tendre/plier les bras", "Trop de charge"] },
  ecarteHalteres: { name: "Écarté haltères", group: "Pectoraux", equipment: "Haltères",
    instructions: "Banc plat, bras légèrement fléchis et fixes. Ouvre en arc de cercle jusqu'au niveau de la poitrine, reviens en rapprochant au-dessus de la poitrine.",
    cues: ["Coudes fléchis et figés", "Arc de cercle", "Étirement contrôlé en bas"],
    mistakes: ["Descendre trop bas", "Plier/tendre les bras"] },
  pecDeck: { name: "Écarté machine (Pec deck)", group: "Pectoraux", equipment: "Machine",
    instructions: "Rapproche les bras devant toi en contractant les pectoraux, reviens lentement en contrôlant l'étirement.",
    cues: ["Dos collé au dossier", "Contraction au centre", "Retour lent"],
    mistakes: ["À-coups", "Hausser les épaules"] },
  devInclineMachine: { name: "Développé incliné machine", group: "Pectoraux", equipment: "Machine",
    instructions: "Poignées au niveau du haut de la poitrine. Pousse vers l'avant/haut sans verrouiller, reviens en contrôlant.",
    cues: ["Omoplates serrées", "Amplitude complète", "Pas de blocage des coudes"],
    mistakes: ["Charge trop lourde", "Décoller le dos"] },

  devMilitaire: { name: "Développé militaire", group: "Épaules", equipment: "Haltères",
    instructions: "Haltères au niveau des épaules. Gaine et pousse au-dessus de la tête, redescends au niveau des oreilles. Évite de cambrer.",
    cues: ["Gaine le tronc", "Trajectoire au-dessus de la tête", "Ne cambre pas le bas du dos"],
    mistakes: ["Cambrure lombaire", "Amplitude trop courte", "Élan des jambes"] },
  shrugs: { name: "Shrugs (trapèzes)", group: "Épaules", equipment: "Haltères",
    instructions: "Hausse les épaules vers les oreilles le plus haut possible, pause, redescends lentement. Ne roule pas les épaules.",
    cues: ["Monte droit vers les oreilles", "Pause en haut", "Descente contrôlée"],
    mistakes: ["Rouler les épaules", "Utiliser les bras"] },
  elevationsLaterales: { name: "Élévations latérales", group: "Épaules", equipment: "Haltères",
    instructions: "Lève les bras sur les côtés jusqu'à l'horizontale, coudes un peu plus hauts que les poignets, redescends lentement. Cible le deltoïde latéral.",
    cues: ["Mène avec les coudes", "Monte jusqu'à l'horizontale", "Pas d'élan du buste"],
    mistakes: ["Trop lourd → balancier", "Hausser les trapèzes"] },
  elevationsFrontales: { name: "Élévations frontales", group: "Épaules", equipment: "Haltères",
    instructions: "Lève un bras (ou les deux) devant toi jusqu'à l'horizontale en contrôlant, redescends. Cible le deltoïde antérieur.",
    cues: ["Bras légèrement fléchi", "Monte jusqu'à l'horizontale", "Pas de balancier"],
    mistakes: ["Se servir du dos", "Charge trop lourde"] },

  tirageVertical: { name: "Tirage vertical (poulie haute)", group: "Dos", equipment: "Poulie",
    instructions: "Tire la barre vers le haut de la poitrine en abaissant/rapprochant les omoplates, buste légèrement incliné en arrière. Tire avec les coudes.",
    cues: ["Coudes vers les hanches", "Serre les omoplates", "Buste stable"],
    mistakes: ["Tirer derrière la nuque", "Se balancer", "Tirer avec les bras seuls"] },
  rowingBarre: { name: "Rowing barre", group: "Dos", equipment: "Barre",
    instructions: "Buste penché ~45°, dos gainé. Tire la barre vers le bas du ventre, coudes vers l'arrière, redescends en contrôlant.",
    cues: ["Dos droit et gainé", "Tire vers le nombril", "Coudes proches du corps"],
    mistakes: ["Dos rond", "Se redresser à chaque rep", "Tirer trop haut"] },
  rowingHaltere: { name: "Rowing haltère (bûcheron)", group: "Dos", equipment: "Haltères",
    instructions: "Un genou/main sur le banc, dos à plat. Tire l'haltère vers la hanche, coude le long du corps, redescends en contrôlant.",
    cues: ["Dos plat parallèle au sol", "Coude vers la hanche", "Contraction en haut"],
    mistakes: ["Tourner le buste", "Tirer avec le biceps seul"] },
  tirageHorizontal: { name: "Tirage horizontal (poulie)", group: "Dos", equipment: "Poulie",
    instructions: "Buste droit, tire la poignée vers le bas du ventre, coudes vers l'arrière, serre les omoplates, reviens en contrôlant.",
    cues: ["Buste droit et stable", "Serre les omoplates", "Coudes le long du corps"],
    mistakes: ["Se balancer", "Arrondir le dos"] },
  pullOver: { name: "Pull-over poulie (bras tendus)", group: "Dos", equipment: "Poulie",
    instructions: "Face à la poulie haute, bras quasi tendus. Abaisse la barre vers les cuisses en gardant les bras tendus, contracte les dorsaux, reviens.",
    cues: ["Bras tendus tout du long", "Initié par les dorsaux", "Gainage du tronc"],
    mistakes: ["Plier les coudes", "Trop de charge"] },
  rearDelt: { name: "Oiseau / arrière d'épaule", group: "Épaules", equipment: "Machine",
    instructions: "Sur machine (reverse pec deck) ou poulie, ouvre les bras vers l'arrière en serrant les omoplates pour cibler l'arrière de l'épaule. Retour lent.",
    cues: ["Coudes légèrement fléchis", "Serre les omoplates", "Mouvement contrôlé"],
    mistakes: ["Charge trop lourde", "Utiliser les trapèzes"] },

  curlHalteres: { name: "Curl haltères", group: "Biceps", equipment: "Haltères",
    instructions: "Fléchis les coudes en remontant vers les épaules sans bouger les coudes, contracte en haut, redescends lentement.",
    cues: ["Coudes fixes près du corps", "Pas d'élan", "Contraction en haut"],
    mistakes: ["Balancer le dos", "Coudes qui avancent"] },
  curlPupitre: { name: "Curl pupitre (machine)", group: "Biceps", equipment: "Machine",
    instructions: "Bras calés sur le pupitre, remonte, contracte, redescends sans tendre brusquement en bas.",
    cues: ["Aisselles posées sur le coussin", "Contraction en haut", "Retour contrôlé"],
    mistakes: ["Décoller les bras", "Lâcher la charge en bas"] },
  extensionPoulie: { name: "Extension triceps poulie", group: "Triceps", equipment: "Poulie",
    instructions: "Coudes collés au corps. Tends les bras vers le bas en contractant les triceps, remonte en contrôlant jusqu'à 90°.",
    cues: ["Coudes collés au corps", "Tends complètement en bas", "Buste stable"],
    mistakes: ["Coudes qui s'écartent", "Se pencher pour pousser"] },
  barreAuFront: { name: "Barre au front", group: "Triceps", equipment: "Barre",
    instructions: "Allongé, barre bras tendus au-dessus du front. Fléchis les coudes vers le front en les gardant fixes, puis tends.",
    cues: ["Coudes fixes", "Descends vers le front", "Contrôle total"],
    mistakes: ["Bouger les coudes", "Descendre trop vite"] },
  curlPoulie: { name: "Curl à la poulie", group: "Biceps", equipment: "Poulie",
    instructions: "Face à la poulie basse, remonte la barre vers les épaules coudes fixes, contracte, redescends lentement. Tension constante.",
    cues: ["Coudes fixes", "Tension continue", "Contraction en haut"],
    mistakes: ["Reculer/balancer", "Coudes qui avancent"] },
  curlHaltereDebout: { name: "Curl haltère debout", group: "Biceps", equipment: "Haltères",
    instructions: "Curl classique en supination, alterné ou simultané. Tourne légèrement le poignet vers l'extérieur en haut, redescends lentement.",
    cues: ["Supination en haut", "Coudes fixes", "Descente contrôlée"],
    mistakes: ["Élan du buste", "Amplitude partielle"] },
  dipsMachine: { name: "Triceps machine (dips)", group: "Triceps", equipment: "Machine",
    instructions: "Pousse vers le bas en tendant les bras pour solliciter les triceps, remonte en contrôlant. Buste droit.",
    cues: ["Buste droit", "Tends bien en bas", "Retour contrôlé"],
    mistakes: ["Amplitude trop courte", "Élan du buste"] },

  // Exercices supplémentaires (bibliothèque + ajout en séance)
  souleveDeTerre: { name: "Soulevé de terre", group: "Dos", equipment: "Barre",
    instructions: "Barre au sol contre les tibias. Dos gainé et droit, pousse dans le sol avec les jambes en gardant la barre proche du corps, verrouille les hanches en haut.",
    cues: ["Dos neutre, gainé", "Barre proche des jambes", "Pousse dans le sol", "Verrouille les hanches"],
    mistakes: ["Dos rond", "Barre qui s'éloigne", "Hyperextension en haut"] },
  fentes: { name: "Fentes", group: "Jambes", equipment: "Haltères",
    instructions: "Un grand pas en avant, descends le genou arrière vers le sol buste droit, repousse. Alterne les jambes.",
    cues: ["Buste droit", "Genou avant dans l'axe du pied", "Descente contrôlée"],
    mistakes: ["Genou avant qui dépasse trop l'orteil", "Buste penché en avant"] },
  mollets: { name: "Mollets debout", group: "Mollets", equipment: "Machine",
    instructions: "Monte sur la pointe le plus haut possible en contractant les mollets, pause, descends lentement en étirant.",
    cues: ["Amplitude complète", "Pause en haut", "Étirement en bas"],
    mistakes: ["Rebondir", "Amplitude écourtée"] },
  facePull: { name: "Face pull", group: "Épaules", equipment: "Poulie",
    instructions: "Corde à hauteur du visage. Tire vers le visage en écartant les mains et en ramenant les coudes hauts, pour l'arrière d'épaule.",
    cues: ["Coudes hauts", "Tire vers le front", "Serre les omoplates"],
    mistakes: ["Trop lourd", "Coudes qui tombent"] },
  crunch: { name: "Crunch", group: "Abdominaux", equipment: "Poids du corps",
    instructions: "Enroule le buste en rapprochant les côtes du bassin en soufflant, redescends lentement. Mouvement court et contracté.",
    cues: ["Enroule la colonne", "Souffle en montant", "Ne tire pas sur la nuque"],
    mistakes: ["Tirer sur la tête", "Mouvement à la hanche"] },
  gainage: { name: "Gainage (planche)", group: "Abdominaux", equipment: "Poids du corps",
    instructions: "Appui avant-bras + pointe des pieds, corps aligné. Gaine abdos et fessiers, ne creuse pas le bas du dos. Tiens la position.",
    cues: ["Corps aligné", "Gaine abdos + fessiers", "Ne creuse pas le dos"],
    mistakes: ["Bassin qui tombe", "Fesses trop hautes"] },
  tractions: { name: "Tractions", group: "Dos", equipment: "Poids du corps",
    instructions: "Suspendu, prise pronation largeur d'épaules. Tire en amenant la poitrine vers la barre, serre les omoplates, redescends en contrôlant.",
    cues: ["Serre les omoplates", "Poitrine vers la barre", "Descente contrôlée"],
    mistakes: ["Amplitude partielle", "Se balancer"] },

  // Ajouts bibliothèque (juin 2026) — disponibles dans la fiche Exercices, le sélecteur "+ Exo" en séance et l'éditeur de séance.
  tirageVerticalMachine: { name: "Tirage vertical machine (pulldown)", group: "Dos", equipment: "Machine",
    instructions: "Règle le coussin de cuisses pour te bloquer, attrape les poignées et assieds-toi cuisses sous le coussin. Tire les poignées vers le bas jusqu'à ce que les coudes soient le long du corps et les mains à hauteur des épaules, en abaissant les omoplates. Remonte en contrôlant l'étirement. Travaille grand dorsal, grand rond, biceps, trapèze inférieur et rhomboïdes.",
    cues: ["Cuisses bien calées sous le coussin", "Tire avec les coudes vers les hanches", "Abaisse et serre les omoplates", "Buste stable, léger gainage"],
    mistakes: ["Tirer avec les bras seuls", "Se balancer / prendre de l'élan", "Remonter trop vite sans contrôler"] },
  hipThrust: { name: "Hip thrust (fessiers)", group: "Jambes", equipment: "Barre",
    instructions: "Haut du dos calé contre un banc, barre sur le pli des hanches (avec coussin), pieds à plat largeur de hanches. Pousse dans les talons pour monter le bassin jusqu'à l'alignement épaules-hanches-genoux, contracte fort les fessiers en haut, redescends en contrôlant.",
    cues: ["Pousse dans les talons", "Contracte les fessiers en haut", "Menton rentré, côtes basses", "Tibias verticaux en haut"],
    mistakes: ["Cambrer le bas du dos en haut", "Amplitude trop courte", "Pieds trop loin ou trop près"] },
  souleveDeTerreRoumain: { name: "Soulevé de terre roumain (ischios)", group: "Jambes", equipment: "Haltères",
    instructions: "Debout, haltères (ou barre) devant les cuisses, jambes quasi tendues (léger fléchi). Pousse les hanches vers l'arrière en descendant la charge le long des jambes jusqu'à l'étirement des ischios, dos droit, puis reviens en contractant fessiers et ischios.",
    cues: ["Hanches vers l'arrière (charnière)", "Dos neutre et gainé", "Charge proche des jambes", "Genoux à peine fléchis"],
    mistakes: ["Arrondir le dos", "Plier les genoux comme un squat", "Descendre trop bas en perdant le dos"] },
  hackSquat: { name: "Hack squat (machine)", group: "Jambes", equipment: "Machine",
    instructions: "Dos et épaules calés contre les appuis, pieds à largeur d'épaules au milieu du plateau. Déverrouille, descends en contrôlant jusqu'à ~90° aux genoux, puis pousse dans les talons sans verrouiller les genoux en haut.",
    cues: ["Dos plaqué contre le dossier", "Genoux dans l'axe des pieds", "Descente à la parallèle", "Pousse sur tout le pied"],
    mistakes: ["Décoller le dos / les fesses", "Genoux qui rentrent", "Amplitude trop courte"] },
  dips: { name: "Dips (barres parallèles)", group: "Triceps", equipment: "Poids du corps",
    instructions: "Bras tendus sur les barres parallèles, corps gainé. Descends en pliant les coudes jusqu'à ce que les épaules arrivent au niveau des coudes, puis pousse pour remonter. Buste droit = triceps ; penché en avant = plus de pectoraux.",
    cues: ["Épaules basses, loin des oreilles", "Coudes vers l'arrière", "Descente contrôlée", "Gaine le tronc"],
    mistakes: ["Descendre trop bas (épaules forcées)", "À-coups en bas", "Hausser les épaules"] },
  curlMarteau: { name: "Curl marteau", group: "Biceps", equipment: "Haltères",
    instructions: "Haltères en prise neutre (paumes face à face, pouces vers le haut). Fléchis les coudes en gardant cette prise marteau, contracte en haut, redescends lentement. Cible le brachial et l'avant-bras.",
    cues: ["Prise neutre tout du long", "Coudes fixes près du corps", "Pas d'élan", "Descente contrôlée"],
    mistakes: ["Balancer le buste", "Coudes qui avancent", "Tourner le poignet"] },
  releveJambes: { name: "Relevé de jambes", group: "Abdominaux", equipment: "Poids du corps",
    instructions: "Suspendu à une barre (ou allongé au sol). Monte les jambes (tendues ou genoux fléchis) en enroulant le bassin vers le haut, contracte les abdos en haut, redescends lentement sans cambrer ni te balancer.",
    cues: ["Enroule le bassin (pas juste lever les jambes)", "Contrôle la descente", "Pas de balancier", "Souffle en montant"],
    mistakes: ["Se balancer / prendre de l'élan", "Cambrer le bas du dos", "Descente trop rapide"] },
};

// Le programme : 5 séances. Chaque exo = 4 séries de travail, reps 6-12 selon l'exo.
// ladder = échelle de charges planifiées (progression au fil des séances).
export const PROGRAM = [
  { name: "Jambes", color: "#FF7A00", summary: "Presse, squat, machines",
    exercises: [
      { ex: "presse", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [100,110,120,130] },
      { ex: "smithSquat", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [100,110], notes: "Sécurité au cran 4." },
      { ex: "squat", sets: 4, rest: 120, repLow: 6, repHigh: 10, ladder: [25,30,35,40], notes: "Indicateur de soutien réglé sur 19." },
      { ex: "legExtension", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [30,35], superset: 1 },
      { ex: "legCurl", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [40,45,50,55,60], superset: 1, notes: "Super set quadri + ischios." },
    ] },
  { name: "Pec", color: "#E23B3B", summary: "Développés et écartés",
    exercises: [
      { ex: "devCoucheHalteres", sets: 4, rest: 90, repLow: 6, repHigh: 12, ladder: [26,28,30,32,34,36,38,40,42,44,46], notes: "Démarrage vers 34." },
      { ex: "devCoucheBarre", sets: 4, rest: 90, repLow: 6, repHigh: 10, ladder: [80,90], notes: "Cran machine 5, +2 pour le support." },
      { ex: "devInclineHalteres", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [18,20,22,24,26,28,30] },
      { ex: "ecartePoulieBasse", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [5,7.5,10] },
      { ex: "ecarteHalteres", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [10,12,14] },
      { ex: "pecDeck", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [40,45,50] },
      { ex: "devInclineMachine", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [40,50] },
    ] },
  { name: "Épaule", color: "#14B8A6", summary: "Développé, élévations, trapèzes",
    exercises: [
      { ex: "devMilitaire", sets: 4, rest: 90, repLow: 6, repHigh: 12, ladder: [12,16,18,20,22,24] },
      { ex: "shrugs", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [7.5,10] },
      { ex: "elevationsLaterales", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [4,6] },
      { ex: "elevationsFrontales", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [6,8,10,12] },
    ] },
  { name: "Dos", color: "#2E7BE6", summary: "Tirages, rowings, dorsaux",
    exercises: [
      { ex: "tirageVertical", sets: 4, rest: 60, repLow: 8, repHigh: 12, ladder: [55,60,65,70] },
      { ex: "rowingBarre", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [15,17.5,20,22.5,25,27.5,30], notes: "Ou unibar = 40." },
      { ex: "rowingHaltere", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [24,26,28,30,32,34,36,38,40] },
      { ex: "tirageHorizontal", sets: 4, rest: 60, repLow: 8, repHigh: 12, ladder: [35,40,45,50,55,60,65,70] },
      { ex: "pullOver", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [70,80,90,100] },
      { ex: "rearDelt", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [60] },
    ] },
  { name: "Bras", color: "#8E44E6", summary: "Biceps & triceps en alternance",
    exercises: [
      { ex: "curlHalteres", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [7.5,10,12.5,13.75] },
      { ex: "curlPupitre", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [30,40] },
      { ex: "extensionPoulie", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [12.5,15] },
      { ex: "barreAuFront", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [5,6.25,7.5] },
      { ex: "curlPoulie", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [17.5,22.5,25] },
      { ex: "curlHaltereDebout", sets: 4, rest: 60, repLow: 10, repHigh: 12, ladder: [12,14,16] },
      { ex: "dipsMachine", sets: 4, rest: 90, repLow: 8, repHigh: 12, ladder: [60] },
    ] },
];

// Articulations à mobiliser selon le muscle (pour l'échauffement 2 min).
export const JOINTS = {
  "Pectoraux": ["épaules","coudes","poignets"], "Épaules": ["épaules","coudes","poignets"],
  "Dos": ["épaules","colonne","hanches"], "Biceps": ["coudes","poignets"], "Triceps": ["coudes","poignets"],
  "Jambes": ["hanches","genoux","chevilles"],
};
